# Generated by Django 6.0.1 on 2026-02-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_productdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Product_Category',
            field=models.CharField(max_length=100),
        ),
    ]
