# Generated by Django 6.0.1 on 2026-02-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_accountdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
