# Generated by Django 6.0.1 on 2026-02-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_alter_accountdb_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdb',
            name='Confrom_Password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
