# Generated by Django 6.0.1 on 2026-03-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Place', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Pin', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Grand_Total', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
